name: Deploy Documentation to GitHub Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["master"]
        paths:
            - "docs/**"
            - ".vitepress/**"
            - ".github/workflows/docs.yaml"
            - "pnpm-lock.yaml"
            - "package.json"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    # Build job
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4.3.1
              with:
                  fetch-depth: 0 # Fetch all history for git commands

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.2.0

            - name: Setup Node.js
              uses: actions/setup-node@v4.4.0
              with:
                  node-version-file: .node-version
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Setup Pages
              uses: actions/configure-pages@v5.0.0

            - name: Build documentation
              run: pnpm docs:build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3.0.1
              with:
                  path: docs/.vitepress/dist

    # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-24.04
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4.0.5
